"""The `viper` command-line interface."""
import argparse
import os
import sys

from . import __version__
from .errors import ViperError
from .runtime import run_source, run_repl_line, _fresh_namespace


def run_file(path: str) -> int:
    script_dir = os.path.dirname(os.path.abspath(path))
    if script_dir not in sys.path:
        sys.path.insert(0, script_dir)
    try:
        with open(path, "r", encoding="utf-8") as f:
            source = f.read()
    except OSError as e:
        print(f"error: cannot read {path!r}: {e}", file=sys.stderr)
        return 1

    try:
        run_source(source, filename=path)
    except ViperError as e:
        print(str(e), file=sys.stderr)
        return 1
    return 0


_BUILD_HEADER = """\
# Generated by Viper (viper build) — https://pypi.org/project/viper-lang/
# Source: {src}
# This file is self-contained: the Viper prelude is inlined below.
import pprint as _pprint
from pathlib import Path as _Path
pp = _pprint.pprint
def read_file(path, encoding="utf-8"): return _Path(path).read_text(encoding=encoding)
def write_file(path, text, encoding="utf-8"): return _Path(path).write_text(text, encoding=encoding)
def clamp(x, lo, hi): return lo if x < lo else hi if x > hi else x
# --- end prelude ---
"""


def build_file(path: str, output: str | None = None) -> int:
    from .codegen import transpile
    try:
        with open(path, "r", encoding="utf-8") as f:
            source = f.read()
    except OSError as e:
        print(f"error: cannot read {path!r}: {e}", file=sys.stderr)
        return 1
    try:
        py_source, _ = transpile(source, path)
    except ViperError as e:
        print(str(e), file=sys.stderr)
        return 1
    out = output or (path[:-3] + ".py" if path.endswith(".vp") else path + ".py")
    with open(out, "w", encoding="utf-8") as f:
        f.write(_BUILD_HEADER.format(src=path))
        f.write(py_source)
    print(f"wrote {out}")
    return 0


def fmt_files(paths: list[str], check: bool = False) -> int:
    from .fmt import format_file
    dirty = 0
    for path in paths:
        try:
            clean = format_file(path, check=check)
        except (OSError, ViperError) as e:
            print(str(e), file=sys.stderr)
            return 1
        if not clean:
            print(f"would reformat {path}")
            dirty += 1
        elif not check:
            pass
    if check and dirty:
        print(f"{dirty} file(s) would be reformatted", file=sys.stderr)
        return 1
    return 0


def _needs_continuation(buffer: str) -> bool:
    """True while a block is open (unbalanced brackets or last non-blank line ends in ':').

    This is much more reliable than the old heuristic that only checked for ':'.
    We also track open brackets so multi-line expressions work correctly.
    """
    # Count unbalanced brackets — open means we're in the middle of an expression
    opens = {"(": ")", "[": "]", "{": "}"}
    closes = set(opens.values())
    stack = []
    in_string = None
    escape = False

    for ch in buffer:
        if escape:
            escape = False
            continue
        if ch == "\\":
            escape = True
            continue
        if in_string:
            if ch == in_string:
                in_string = None
            continue
        if ch in ('"', "'"):
            in_string = ch
            continue
        if ch in opens:
            stack.append(opens[ch])
        elif ch in closes:
            if stack and stack[-1] == ch:
                stack.pop()

    if stack:  # Unbalanced brackets
        return True

    # Check if last non-empty line ends with a block-opening colon
    lines = [ln for ln in buffer.splitlines() if ln.strip()]
    if not lines:
        return False
    last = lines[-1].rstrip()
    # Strip inline comments before checking
    if "#" in last:
        last = last[:last.index("#")].rstrip()
    return last.endswith(":")


def _install_repl_completion(ns: dict) -> None:
    """Tab-completion over keywords, builtins, and live names. Best-effort."""
    try:
        import readline
    except ImportError:
        return
    from .keywords import KEYWORDS, BUILTINS

    def completer(text, state):
        options = [w for w in KEYWORDS + BUILTINS + list(ns)
                   if w.startswith(text)]
        return options[state] if state < len(options) else None

    readline.set_completer(completer)
    readline.parse_and_bind("tab: complete")


def repl() -> int:
    print(f"Viper {__version__} — type Ctrl-D to exit.")
    ns = _fresh_namespace()
    _install_repl_completion(ns)
    buffer = ""
    while True:
        prompt = "... " if buffer else ">>> "
        try:
            line = input(prompt)
        except EOFError:
            print()
            return 0
        except KeyboardInterrupt:
            print("\n(interrupted)")
            buffer = ""
            continue

        # An empty line after a block flushes the buffer
        if not line.strip() and buffer:
            try:
                run_repl_line(buffer, ns)
            except ViperError as e:
                print(str(e), file=sys.stderr)
            buffer = ""
            continue

        buffer = buffer + line + "\n" if buffer else line + "\n"

        if _needs_continuation(buffer):
            continue

        # Only flush if the block is closed (blank line or no open colon)
        if buffer.rstrip().endswith(":"):
            # Still opening a block — keep reading
            continue

        try:
            run_repl_line(buffer, ns)
        except ViperError as e:
            print(str(e), file=sys.stderr)
        buffer = ""


def doctor() -> int:
    """Check the whole installation and say exactly what to fix."""
    import json
    import platform
    import shutil

    ok = True

    def check(label: str, passed: bool, fix: str = "") -> None:
        nonlocal ok
        print(f"[{'OK  ' if passed else 'FAIL'}] {label}")
        if not passed:
            ok = False
            if fix:
                print(f"       fix: {fix}")

    print("viper doctor — checking your installation")
    print(f"       python: {sys.executable}")
    print()
    check(f"Python {platform.python_version()} (needs 3.10+)",
          sys.version_info >= (3, 10),
          "install Python 3.10+ from https://www.python.org/downloads/")
    try:
        import lark
        check(f"lark {getattr(lark, '__version__', '?')} (parser)", True)
    except ImportError:
        check("lark (parser)", False, "pip install 'lark>=1.1.0'")
    try:
        import pygls
        check(f"pygls {getattr(pygls, '__version__', '?')} (language server -> editor autocompletion)", True)
    except ImportError:
        check("pygls (language server -> editor autocompletion)", False,
              'pip install "pygls>=2.1,<3"   (or just re-run install.ps1 / install.sh)')
    exe = shutil.which("viper")
    check(f"viper on PATH ({exe or 'NOT FOUND'})", exe is not None,
          "re-run install.ps1 / install.sh, then open a NEW terminal")

    home = os.path.expanduser("~")
    for editor in (".vscode", ".cursor"):
        ext_root = os.path.join(home, editor, "extensions")
        if not os.path.isdir(os.path.join(home, editor)):
            continue  # this editor isn't installed — skip silently
        found = None
        if os.path.isdir(ext_root):
            for d in sorted(os.listdir(ext_root)):
                if d.startswith("viper-lang.viper"):
                    found = d
        if not found:
            check(f"{editor[1:]} extension", False,
                  "re-run install.ps1 / install.sh (or: python editor/vscode/register_extension.py)")
            continue
        version = "?"
        try:
            with open(os.path.join(ext_root, found, "package.json"), encoding="utf-8") as f:
                version = json.load(f).get("version", "?")
        except OSError:
            pass
        has_client = os.path.isfile(os.path.join(ext_root, found, "out", "extension.js"))
        check(f"{editor[1:]} extension v{version} (LSP client bundled: {'yes' if has_client else 'NO'})",
              has_client,
              "extension is outdated — re-run install.ps1 / install.sh, then restart the editor")

        # A folder in extensions/ is NOT enough: modern VS Code/Cursor only
        # load extensions listed in extensions.json and absent from .obsolete.
        # An unregistered copy fails silently — the #1 cause of "autocompletion
        # suddenly stopped working".
        registered = True  # editors without a registry file scan folders directly
        reg_file = os.path.join(ext_root, "extensions.json")
        if os.path.isfile(reg_file):
            try:
                with open(reg_file, encoding="utf-8") as f:
                    entries = json.load(f)
                registered = any(
                    isinstance(e, dict) and (
                        e.get("relativeLocation") == found
                        or str((e.get("location") or {}).get("path", ""))
                        .rstrip("/").endswith("/" + found)
                    )
                    for e in entries
                )
            except (OSError, ValueError):
                registered = False
        try:
            with open(os.path.join(ext_root, ".obsolete"), encoding="utf-8") as f:
                if json.load(f).get(found):
                    registered = False  # editor flagged the folder for deletion
        except (OSError, ValueError):
            pass
        check(f"{editor[1:]} extension registered in extensions.json (editor actually loads it)",
              registered,
              "run: python editor/vscode/register_extension.py  (or re-run install.ps1 / install.sh), "
              "then fully quit and reopen the editor")

    print()
    if ok:
        print("everything looks good. If the editor still misbehaves: Reload Window")
        print("(Ctrl+Shift+P > Reload Window), then check Output > Viper Language Server.")
    else:
        print("fix the FAIL lines above, then run 'viper doctor' again.")
    return 0 if ok else 1


def _start_lsp() -> int:
    try:
        from . import lsp
    except ImportError:
        print("the Viper language server needs the optional 'pygls' dependency.",
              file=sys.stderr)
        print("install it with:  pip install 'viper-lang[lsp]'", file=sys.stderr)
        return 1
    lsp.start()
    return 0


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(prog="viper", description="The Viper language.")
    ap.add_argument("--version", action="version",
                    version=f"viper {__version__}")
    ap.add_argument("--lsp", action="store_true",
                    help="run the Viper language server (for editors)")
    sub = ap.add_subparsers(dest="command")

    run_p = sub.add_parser("run", help="run a .vp file")
    run_p.add_argument("file")

    sub.add_parser("repl", help="start the interactive REPL")

    build_p = sub.add_parser("build", help="transpile a .vp file to a standalone .py file")
    build_p.add_argument("file")
    build_p.add_argument("-o", "--output", help="output path (default: <file>.py)")

    fmt_p = sub.add_parser("fmt", help="format .vp files in place")
    fmt_p.add_argument("files", nargs="+")
    fmt_p.add_argument("--check", action="store_true",
                       help="don't write; exit 1 if anything would change")

    help_p = sub.add_parser("help", help="interactive tutorial, or reference for a topic")
    help_p.add_argument("topic", nargs="?", help="a topic, e.g. match, pipe, fn")

    sub.add_parser("topics", help="list the available help topics")

    sub.add_parser("doctor", help="diagnose installation / editor-integration problems")

    # Shebang / direct-run support: `viper script.vp` == `viper run script.vp`
    raw = sys.argv[1:] if argv is None else list(argv)
    if raw and raw[0].endswith(".vp"):
        return run_file(raw[0])

    args = ap.parse_args(argv)

    if args.lsp:
        return _start_lsp()
    if args.command == "run":
        return run_file(args.file)
    if args.command == "build":
        return build_file(args.file, args.output)
    if args.command == "fmt":
        return fmt_files(args.files, check=args.check)
    if args.command == "doctor":
        return doctor()
    if args.command == "help":
        if args.topic in (None, "topics"):
            if args.topic == "topics":
                from .help import list_topics
                return list_topics()
            from .tutorial import run_tutorial
            return run_tutorial()
        from .help import show_topic
        return show_topic(args.topic)
    if args.command == "topics":
        from .help import list_topics
        return list_topics()
    return repl()


if __name__ == "__main__":
    sys.exit(main())
